language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
node_js:
    - "10.19.0"
branches:
    only:
        - master
before_script:
    - nvm install v10.19.0
    - npm install -g @ionic/cli cordova 
    - npm install
script:
    - ionic cordova build android --prod
